### ISSUE TITLE
line 23476 of configure has too many #'s

### ISSUE THREAD

**Issue by themaddoctor** [libyal/libfwsi#10]
23466-ac_compiler_gnu=$ac_cv_c_compiler_gnu
23467-
23468-       cat confdefs.h - <<_ACEOF >conftest.$ac_ext
23469-/* end confdefs.h.  */
23470-#include <libclocale/features.h>
23471-int
23472-main ()
23473-{
23474-#if !defined( LIBCLOCALE_HAVE_WIDE_CHARACTER_TYPE ) || ( LIBCLOCALE_HAVE_WIDE_CHARACTER_TYPE != 1 )
23475-#error LIBCLOCALE_HAVE_WIDE_CHARACTER_TYPE not defined
23476:##endif

This causes the test program to fail every time.

**Comment by themaddoctor** [comment]
Which is a weird test to do, since it doesn't use libclocale.

**Comment by joachimmetz** [comment]
Could you attach config.log. This looks to be the test to see if a shared version of libclocale matches the configuration that is required by libfwsi.

> Which is a weird test to do, since it doesn't use libclocale.

This might be a left over.

**Comment by themaddoctor** [comment]
[config.log](https://github.com/libyal/libfwsi/files/1692615/config.log)
