### ISSUE TITLE
provide pre-built wheels for the main OSses and Python

### ISSUE THREAD

**Issue by pombredanne** [libyal/libfwsi#19]
It would be nice to have pre-built wheels for Linux, macOS and Windows for Python 3.7/3.8/3.9/3.10.
If you like I can send a patch to run this in the CI as GH action.
FWIW, I use this as an example for a project that I co-maintain https://github.com/WojciechMula/pyahocorasick/blob/master/.github/workflows/test-and-build.yml (Stolen with credits from Google's brotli repo)

**Comment by joachimmetz** [comment]
Closing this issue in favor of https://github.com/libyal/libyal/issues/94
