### ISSUE TITLE
Extend pyfwsi to provide support for more shell item types

### ISSUE THREAD

**Issue by lotansery7** [libyal/libfwsi#21]
"pyfwsi" it exposes 4 types of shell items: volume, file_entry, network_location and root_folder however it would be beneficial to have support for:

- GUID: Control panel
- Control Panel Category
- Variable: Users property view
- Users property view: Drive letter
- Users Files Folder
- Variable
- Users property view

Is it possible to add support for those shell types as well?

Thanks!

**Comment by lotansery7** [comment]
In [UsrClass.zip](https://github.com/libyal/libfwsi/files/14361980/UsrClass.zip) you can find examples for:
- GUID: Control panel
- Control Panel Category
- Users property view: Drive letter
- Users Files Folder
- Users property view

In [NTUSER_BAGMRU.zip](https://github.com/libyal/libfwsi/files/14362014/NTUSER_BAGMRU.zip) you can find examples for:
- Variable: Users property view
- Users property view

I will try to get an example of "Variable" that I can share.

Thank you!

**Comment by joachimmetz** [comment]
@lotansery7 what is the origin of these files? S-1-5-21-2734969515-1644526556-1039763013-1001 from one of these seems to be referenced in a text book

**Comment by lotansery7** [comment]
I took it from regipy repo test files

**Comment by lotansery7** [comment]
Ok I will create a clean sample then

**Comment by joachimmetz** [comment]
> Ok I will create a clean sample then

thx to be explicit I just need to know what the "types" refer to in terms of https://github.com/libyal/libfwsi/blob/main/documentation/Windows%20Shell%20Item%20format.asciidoc to see if it is already supported but just need to be exposed via the API/Python bindings or if it is a newly observed one

**Comment by lotansery7** [comment]
In [Usrclass_1.zip](https://github.com/libyal/libfwsi/files/14372376/Usrclass_1.zip) you can find examples for:

- GUID: Control panel
- Control Panel Category
- Variable: Users property view

In  [Usrclass_2.zip](https://github.com/libyal/libfwsi/files/14372387/Usrclass_2.zip) you can find examples for:
- GUID: Control panel
- Control Panel Category
- Users Files Folder
- Users property view
- Users property view: Drive letter

In [Usrclass_3.zip](https://github.com/libyal/libfwsi/files/14372394/Usrclass_3.zip) you can find examples for:
- GUID: Control panel
- Control Panel Category
- Users property view
- Variable

Thanks

**Comment by joachimmetz** [comment]
@lotansery7 thanks much appreciated, I'll have a look as soon as time permits and might ask some follow up questions. Some and other types are supported by the library (https://github.com/libyal/libfwsi/tree/main/libfwsi) just not yet exposed, adding them should be relatively straightforward. I'll see what other types remain.

**Comment by joachimmetz** [comment]
"Variable: Users property view", "Users property view", "Users property view: Drive letter" all appear to be the same shell item type.

**Comment by lotansery7** [comment]
Thank you so much!
But, can I query on these using "pyfwsi"?

**Comment by joachimmetz** [comment]
> But, can I query on these using "pyfwsi"?

not yet, when there is a new release, more research is needed for some of the shell item types (the other tool might be making assumptions that don't correspond to the actual data)

**Comment by joachimmetz** [comment]
* the "Users Files Folder" is likely a file entry shell item with a "Profile" (dffacdc5-679f-4156-8947-c5c76bc0b67f) delegate folder 
* "Users property view: Drive letter", is likely a volume shell item with a "Removable Drives" (f5fb2c77-0e2f-4a16-a381-3e560c68bc83) delegate folder

**Comment by joachimmetz** [comment]
@lotansery7 give libfwsi-experimental-20240225 a try. Without actual documentation without what these type names actually mean I can only guess.

**Comment by lotansery7** [comment]
I tried but I still see the same shell item types:
![image](https://github.com/libyal/libfwsi/assets/76725030/6d97d3f9-9264-4f69-adfd-0b0ef311310f)

**Comment by lotansery7** [comment]
I tried it, now I see that all the shell items are recognized as "item" type and not "volume\file_entry\network_location\root"_folder as before

**Comment by joachimmetz** [comment]
@lotansery7 what exactly did you try?

**Comment by lotansery7** [comment]
![image](https://github.com/libyal/libfwsi/assets/76725030/ff0597e1-ed90-4ffb-8275-9a3ac6cb79de)

**Comment by joachimmetz** [comment]
The following is working for me https://github.com/libyal/winreg-kb/blob/main/scripts/mru.py#L139 check if you have the right version

**Comment by lotansery7** [comment]
"users_property_view" looks good! thanks
But the "control_panel_category" and "control_panel_item" doesn't give me the details:
![image](https://github.com/libyal/libfwsi/assets/76725030/249fe3d3-9a3c-4c9d-a17b-4885200f201f)

**Comment by lotansery7** [comment]
Also "Variable: Users property view" is not recognize: (example from Usrclass_1.zip)
![image](https://github.com/libyal/libfwsi/assets/76725030/cbe57d76-00f7-4cc6-9b6e-f87a70ca36a3)
![image](https://github.com/libyal/libfwsi/assets/76725030/e310ebd9-d6b5-48d7-ad72-f256b29c269c)

**Comment by joachimmetz** [comment]
> Also "Variable: Users property view" is not recognize: (example from Usrclass_1.zip)

What is "Variable: Users property view"? also see https://github.com/libyal/libfwsi/issues/21#issuecomment-1962337543

This looks like a network location shell item to me

**Comment by lotansery7** [comment]
> > But the "control_panel_category" and "control_panel_item" doesn't give me the details:
> 
> Have a closer look there is an "identifier" attribute now that refers to the category or item identifier (also see https://github.com/libyal/libfwsi/blob/main/documentation/Windows%20Shell%20Item%20format.asciidoc#432-control-panel-category-shell-item , https://learn.microsoft.com/en-us/windows/win32/shell/controlpanel-canonical-names?redirectedfrom=MSDN and https://github.com/libyal/libfwsi/blob/main/documentation/Windows%20Shell%20Item%20format.asciidoc#432-control-panel-category-shell-item)

I see the GUID translation but I have just identifier:
![image](https://github.com/libyal/libfwsi/assets/76725030/3272a9a3-f525-4f38-9752-ca777823ffef)

**Comment by joachimmetz** [comment]
You need to parse the property store data, which is another data format.

**Comment by joachimmetz** [comment]
Have a look at the script https://github.com/libyal/winreg-kb/blob/main/scripts/mru.py#L150 I mentioned earlier, it uses a WIP project named libfwps

**Comment by lotansery7** [comment]
Cool I will try, thanks!

**Comment by lotansery7** [comment]
> [Usrclass_3.zip](https://github.com/libyal/libfwsi/files/14372394/Usrclass_3.zip)

Thanks the parsing of the property store data is working for me now :) 

Now I am trying to parse the "Variable" from [Usrclass_3.zip](https://github.com/libyal/libfwsi/files/14372394/Usrclass_3.zip) but I have no "delegate_folder_identifier" or "property_store_data":
![image](https://github.com/libyal/libfwsi/assets/76725030/cc6cc43a-e7a8-45fc-bf0a-107305fb6e6f)

**Comment by lotansery7** [comment]
> * "Users Files Folder" is likely a file entry shell item with a "Profile" (dffacdc5-679f-4156-8947-c5c76bc0b67f) delegate folder
> * "Users property view" is likely a Users property view shell item with a "Search Folder" (04731b67-d933-450a-90e6-4acd2e9408fe) delegate folder
> * "Users property view: Drive letter", is likely a volume shell item with a "Removable Drives" (f5fb2c77-0e2f-4a16-a381-3e560c68bc83) delegate folder
> * "Variable: Users property view" is likely a Users property view shell item
> * Variable is likely a Users property view shell item with a known folder identifier and without properties

Thanks the parsing of the property store data is working for me now :) 

Now I am trying to parse the "Variable" from [Usrclass_3.zip](https://github.com/libyal/libfwsi/files/14372394/Usrclass_3.zip) but I have no "delegate_folder_identifier" or "property_store_data":
![image](https://github.com/libyal/libfwsi/assets/76725030/cc6cc43a-e7a8-45fc-bf0a-107305fb6e6f)

**Comment by joachimmetz** [comment]
Not sure what "variable" applies to in this context. Format wise it is comparable to a users property view without a property store and with the pictures known folder identifier. It has no delegate, currently the known folder identifier is not yet exposed to the Python binding. 

```
libfwsi_users_property_view_values_read_data: class type indicator	: 0x00
libfwsi_users_property_view_values_read_data: unknown1			: 0x00
libfwsi_users_property_view_values_read_data: data size			: 26
libfwsi_users_property_view_values_read_data: data signature		: 0x23febbee
libfwsi_users_property_view_values_read_data: property store size	: 0
libfwsi_users_property_view_values_read_data: identifier size		: 16
libfwsi_users_property_view_values_read_data: identifier data:
00000000: 5d 01 dd 0d 6c b0 d5 45  8c 4c f5 97 13 85 46 39   ]...l..E .L....F9

libfwsi_users_property_view_values_read_data: known folder identifier	: {0DDD015D-B06C-45D5-8C4C-F59713854639}
libfwsi_users_property_view_values_read_data: known folder name		: Unknown
libfwsi_users_property_view_values_read_data: property set data:

libfwsi_users_property_view_values_read_data: unknown1 size		: 0

Shell item:
	Item type							: Users Property View
```

**Comment by lotansery7** [comment]
So as far as I understand this shell item can't be parse for now?

**Comment by lotansery7** [comment]
Understood, but the known folder identifier is the one I need to be able to translate it to a readable shell item. For now I can just call it "Unknown"

**Comment by joachimmetz** [comment]
> There is maybe an estimated time when it will be supported?

When time permits, this is all best effort. The source is open, feel free to change it to your needs.

The issue is that this part of the format is not well understood. Just came across another variant of users properties views with 1060 bytes of "identifier data".

**Comment by lotansery7** [comment]
Ok, thank you very much!

**Comment by joachimmetz** [comment]
Pushed a new release, should be an optional know_folder_identifier property now.

**Comment by lotansery7** [comment]
Works perfect now, thanks!
