### ISSUE TITLE
missing declaration libfwsi_item_copy_from_byte_stream

### ISSUE THREAD

**Issue by ant1** [libyal/libfwsi#4]
When building libregf 20150701 with libfwsi 20150614,  I have the following warning:

report_handle.c:1843:6: warning: implicit declaration of function 'libfwsi_item_copy_from_byte_stream' is invalid in C99 [-Wimplicit-function-declaration]
        if( libfwsi_item_copy_from_byte_stream(
            ^
1 warning generated.

This may lead to the same kind of bug as https://github.com/libyal/liblnk/issues/2

**Comment by joachimmetz** [comment]
I'll add the function to the include file.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libfwsi/commit/9cac866d74099b2f84b47e180c03e2fa79d852b8
