### ISSUE TITLE
File size if the size excess 0xFFFFFFFF (32 bits)

### ISSUE THREAD

**Issue by AlexisTM** [libyal/libfwsi#5]
Dear,

Answer to a question of [Windows Shell documentation, line 381](https://github.com/libyal/libfwsi/blob/master/documentation/Windows%20Shell%20Item%20format.asciidoc#network_location_shell_item#l381)

According to the [Microsoft website](https://msdn.microsoft.com/en-us/library/dd891343.aspx), the if the filesize excess the 32 bits, then we should take the *32 LEAST SIGNIFICANT BITS*

**Comment by joachimmetz** [comment]
A "Windows Shell Item" (or "File entry shell item – pre Windows XP" for that matter) is not the same as a "Shell Link Header", for the latter see [liblnk](https://github.com/libyal/liblnk/blob/master/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#2-file-header)

**Comment by joachimmetz** [comment]
Don't get me wrong you could be right about the the behavior being the same as for the Shell Link Header, but that would need to be proven by tests.
